torchrun --standalone --nproc_per_node=8 pretokenize_tar.py \
  --json_path "/opt/tiger/Emu3.5-NAR/GPT4o-Image/text_to_image.json" \
  --image_root "/opt/tiger/Emu3.5-NAR/GPT4o-Image" \
  --output_dir "/opt/tiger/Emu3.5-NAR/GPT4o-Image_pretok_32" \
  --split "text_to_image" \
  --vq_path "./weights/Emu3.5-VisionTokenizer" \
  --vq_type ibq \
  --vq_device cuda \
  --grid_height 32 \
  --grid_width 32 \
  --output_prefix "gpt4o_t2i_32" \
  --shard_size 5000